version: 2.1

orbs:
  python: circleci/python@0.2.1
  poetry: frameio/poetry@0.14.3

workflows:
  ci:
    jobs:
      - poetry/install
      - poetry/shell:
          args: pylint myapp/.
          requires:
            - poetry/install
