version: 2.1

orbs:
  python: circleci/python@0.2.1
  poetry: frameio/poetry@0.14.3

jobs:
  - poetry/build
  - poetry/shell:
      args: pylint terminalgame/.
      requires:
        - poetry/build

workflows:
  main:
    jobs:
      - build-and-test
